<?php

if (function_exists('acf_add_local_field_group')):
	acf_add_local_field_group([
		'key' => 'group_5f95e445eea95',
		'title' => 'Signposts',
		'fields' => [
			[
				'key' => 'field_5f95e4589ee72',
				'label' => 'Signposts',
				'name' => 'homepage_signposts',
				'type' => 'repeater',
				'instructions' =>
					'A place for any funky bits and bobs we want to highlight on the homepage that aren\'t meets.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'collapsed' => 'field_5f95e4d79ee74',
				'min' => 0,
				'max' => 3,
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => [
					[
						'key' => 'field_5f95e50a9ee76',
						'label' => 'Link',
						'name' => 'signpost_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
					],
					[
						'key' => 'field_5f95e4969ee73',
						'label' => 'Image',
						'name' => 'signpost_image',
						'type' => 'image_crop',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'crop_type' => 'hard',
						'target_size' => 'custom',
						'width' => 670,
						'height' => 335,
						'preview_size' => 'medium',
						'force_crop' => 'yes',
						'save_in_media_library' => 'yes',
						'retina_mode' => 'no',
						'save_format' => 'object',
						'library' => 'all',
					],
					[
						'key' => 'field_5f95e4d79ee74',
						'label' => 'Heading',
						'name' => 'signpost_heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'field_5f95e4f59ee75',
						'label' => 'Blurb',
						'name' => 'signpost_blurb',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					],
				],
			],
		],
		'location' => [
			[
				[
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				],
			],
		],
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	]);
endif;
